version: "3"
services:
  django-rest:
    build: ./server_django
    ports:
    - 8000:8000
    volumes:
    - ./server_django:/usr/src/app
  react-app:
    build: ./react-app
    ports:
    - 3000:3000
    volumes:
    - ./react-app:/usr/src/app
    - /usr/src/app/node_modules
