version: "3"
services:
  postgres-db:
    build:
      context: ./db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
    - ./db/data/postgres:/var/lib/postgresql/data
    networks:
      - front-tier
  # django-rest:
  #   build: ./django_server
  #   ports:
  #   - 8100:8000
  #   volumes:
  #   - ./django_server:/usr/src/app
  #   - /usr/src/app/Pipfile
  #   - /usr/src/app/Pipfile.lock
  #   networks:
  #     - front-tier

  # react-app:
  #   build: ./react-app
  #   ports:
  #   - 3000:3000
  #   volumes:
  #   - ./react-app:/usr/src/app
  #   - /usr/src/app/node_modules
networks:
  front-tier:
